steps:
- name: 'hashicorp/terraform:light'
  args: ['init']
  
- name: 'hashicorp/terraform:light'
  args: ['apply', '-auto-approve']
  env:
  - 'GOOGLE_PROJECT_ID=webx-424701'
  - 'GOOGLE_REGION=us-central1'
  - 'GOOGLE_CREDENTIALS=${_GOOGLE_CREDENTIALS}'
  secretEnv: ['GOOGLE_CREDENTIALS']
options:
  logging: CLOUD_LOGGING_ONLY
